name: FreeImageRe

on:
  push:
    paths:
      - FreeImageRe/**
      - .github/workflows/FreeImageRe.yml

jobs:
  ci:
    uses: ./.github/workflows/_build.yml
    with: { lib: FreeImageRe, version: v0.12.6 }
    secrets: inherit
    # passes GITHUB_TOKEN automatically
