name: libpng

on:
  push:
    paths:
      - libpng/**
      - .github/workflows/libpng.yml

jobs:
  ci:
    uses: ./.github/workflows/_build.yml
    with: { lib: libjpeg, version: v0.12.1 }
    secrets: inherit
